# syntax=docker/dockerfile:1

FROM ubuntu:26.04 AS builder
LABEL maintainer="R2 Rationality <info@r2rationality.com>"
ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/Berlin

RUN --mount=type=cache,id=turbocardano-test-apt-cache-resolute,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,id=turbocardano-test-apt-lib-resolute,target=/var/lib/apt,sharing=locked \
    rm -f /etc/apt/apt.conf.d/docker-clean && \
    apt-get update && \
    apt-get install -y --no-install-recommends \
        build-essential \
        ca-certificates \
        cmake \
        gdb \
        gnupg \
        less \
        libboost-url1.83-dev \
        libboost1.83-all-dev \
        libbotan-3-dev \
        libfmt-dev \
        libsecp256k1-dev \
        libsodium-dev \
        libspdlog-dev \
        libssl-dev \
        libzstd-dev \
        ninja-build \
        pkg-config \
        screen \
        sudo \
        tzdata \
        vim-nox && \
    ln -snf "/usr/share/zoneinfo/${TZ}" /etc/localtime && \
    echo "${TZ}" > /etc/timezone

RUN useradd --create-home --shell /bin/bash --groups sudo dev && \
    echo "dev ALL=(ALL:ALL) NOPASSWD:ALL" > /etc/sudoers.d/dev && \
    chmod 0440 /etc/sudoers.d/dev && \
    install -d -o dev -g dev /home/dev/tada

COPY --chown=dev:dev 3rdparty /home/dev/tada/3rdparty
COPY --chown=dev:dev src /home/dev/tada/src
COPY --chown=dev:dev lib /home/dev/tada/lib
COPY --chown=dev:dev etc /home/dev/tada/etc
COPY --chown=dev:dev data /home/dev/tada/data
COPY --chown=dev:dev test /home/dev/tada/test
COPY --chown=dev:dev CMakeLists.txt /home/dev/tada/CMakeLists.txt

USER dev
WORKDIR /home/dev/tada
RUN cmake -B build -GNinja && cmake --build build -j -t tada

FROM ubuntu:26.04
LABEL maintainer="R2 Rationality <info@r2rationality.com>"
ARG DEBIAN_FRONTEND=noninteractive

RUN --mount=type=cache,id=turbocardano-test-apt-cache-resolute,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,id=turbocardano-test-apt-lib-resolute,target=/var/lib/apt,sharing=locked \
    rm -f /etc/apt/apt.conf.d/docker-clean && \
    apt-get update && \
    apt-get install -y --no-install-recommends \
        libatomic1 \
        libboost-atomic1.83.0 \
        libboost-container1.83.0 \
        libboost-context1.83.0 \
        libboost-coroutine1.83.0 \
        libboost-json1.83.0 \
        libboost-stacktrace1.83.0 \
        libboost-thread1.83.0 \
        libboost-url1.83.0 \
        libbotan-3-10 \
        libfmt10 \
        libnuma1 \
        libsecp256k1-6 \
        libsodium23 \
        libspdlog1.15 \
        libssl3t64 \
        libzstd1 \
        sudo

RUN useradd --create-home --shell /bin/bash --home-dir /opt/tada --groups sudo tada && \
    echo "tada ALL=(ALL:ALL) NOPASSWD:ALL" > /etc/sudoers.d/tada && \
    chmod 0440 /etc/sudoers.d/tada && \
    install -d -o tada -g tada /opt/tada/data /opt/tada/log

COPY --chmod=0755 docker-test.sh /opt/tada/bin/docker-start.sh
COPY --from=builder /home/dev/tada/build/tada /opt/tada/bin/tada
COPY --from=builder /home/dev/tada/etc /opt/tada/etc

USER tada
WORKDIR /opt/tada
ENV TURBO_LOG_PATH=/opt/tada/log/tada.log
ENTRYPOINT ["/opt/tada/bin/docker-start.sh"]
